### PR TITLE
Rewrite and update for v2 libraries

### PR DESCRIPTION
**Pull request by ashquarky**
Updated nex libraries to their new v2 counterparts, and rewrite for the new API as appropriate.

Removed a lot of dead code, notably NEX ranking, subscriptions, and the database connection for rankings. As far as I can tell these were unused. Some maybe contentious cuts are registerSecureServerNEXProtocols and GetPlayingSession.

I'm pretty new to NEX development so I could have easily missed something important, please review closely! Tested working with a Wii U and Cemu instance on my LAN, was able to play multiplayer worlds.

### CODE REVIEW

**Comment by ashquarky** [comment]
Needs https://github.com/PretendoNetwork/nex-protocols-common-go/pull/29

**Comment by jonbarrow** [comment]
Overall looks good to me. Will wait to merge as it relies on another PR. I didn't notice any glaring issues, but maybe we should discuss internally about establishing some patterns for setting the servers up now that we're moving to v2? That way every server is more or less familiar to navigate

What I mean by that is how there's also a friends server v2 PR (https://github.com/PretendoNetwork/friends/pull/10/), and we both do the same kinds of changes but in slightly different ways (like your use of `InitAccounts`)

Establishing some patterns here sounds like it would be a good idea? Not sure if that should be done in these PRs though. @DaniElectra @shutterbug2000 thoughts?

**Comment by DaniElectra** [comment]
> Establishing some patterns here sounds like it would be a good idea? Not sure if that should be done in these PRs though

I agree, we should set patterns among the servers so that we can keep things consistent. For what I have seen, this version of the Minecraft server with the rewrite is based on the MK7/LM2 codebase I have worked on but with its own additions like the `InitAccounts` function

We could discuss the details on Discord, and then comment them on this discussion

**Comment by ashquarky** [comment]
The library PR is in and the modules are updated, so this is ready to merge.

**Comment by Fefedu973** [comment]
It is nice to see some updates on the minecraft online support. I hope to see it working soon on the network. Thanks for your amazing work everyone !

**Comment by ashquarky** [comment]
I think this is ready to merge for deployment into test now

**Review by DaniElectra — APPROVED** [review]

**Comment by jonbarrow** [comment]
Dani approves, I hit the button :+1:

**Pull request merged**
